name: Terraform Deploy

on:
  workflow_dispatch: # Permite ejecutar manualmente el workflow desde GitHub
    inputs:
      aws_access_key_id:
        description: "AWS Access Key ID"
        required: true
      aws_secret_access_key:
        description: "AWS Secret Access Key"
        required: true

jobs:
  deploy:
    name: Terraform Plan and Apply
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.10.4 # Cambia según la versión que necesites

      - name: Package Lambda
        run: |
          mkdir -p build
          zip -j build/lambda.zip lambda/index.js

      # Configurar credenciales de AWS usando los inputs proporcionados
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ inputs.aws_access_key_id }}
          aws-secret-access-key: ${{ inputs.aws_secret_access_key }}
          aws-region: eu-central-1

      - name: Validate Terraform Installation
        run: terraform version

      - name: Initialize Terraform
        run: terraform init

      - name: Download Terraform State
        uses: actions/download-artifact@v4
        with:
          name: terraform-state
        continue-on-error: true

      - name: Terraform Plan
        run: terraform plan -out=tfplan

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        continue-on-error: true

      - name: Save Terraform State
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-state
          path: terraform.tfstate
